apiVersion: apps/v1 
kind: Deployment 
metadata:
 name: backend
 labels:
     app: backend
     type: backend 
spec:
  template:
    metadata:
     name: backend
     labels:
        app: backend
        type: backend
    spec:
      containers:
      - name: backend
        image: snap032/backend:latest
        env:
         - name: PETCLINIC_JDBC_URL
           value: jdbc:postgresql://postgresql/petclinic
         - name: PETCLINIC_JDBC_USER
           value: root
         - name: PETCLINIC_JDBC_PASSWORD
           value: org.hibernate.dialect.PostgreSQLDialect
         - name: PETCLINIC_JDBC_DIALECT
           value: org.hibernate.dialect.PostgreSQLDialect
         - name: POSTGRES_PASSWORD
           value: root
         - name: POSTGRES_DB
           value: postgres
         - name: POSTGRES_DATABASE
           value: postgres
         - name: POSTGRES_USER
           value: root

  replicas: 3
  selector:
     matchLabels:
        type: backend
  strategy:
    type: Recreate
---

apiVersion: v1 
kind: Service 
metadata:
    name: service-backend 
spec:
    type: NodePort
    ports:
     - targetPort: 8080
       port: 8080
       nodePort: 30016
    selector:
       app: backend
       type: backend
    sessionAffinity: None
    type: NodePort
